<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\Core\Entity\EntityInterface;
use Drupal\webform\Entity\WebformSubmission;

/**
 * Implements hook_entity_create().
 */
function jix_newsletter_entity_create(EntityInterface $entity)
{
    if ($entity instanceof WebformSubmission) {
        Drupal::logger('jix_newsletter')->info('WebformId: ' . $entity->getWebform()->id());
    }
}

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function jix_newsletter_webform_submission_create(EntityInterface $entity)
{
    Drupal::logger('jix_newsletter')->info('WebformBundle: ' . $entity->bundle());
}